### ISSUE TITLE
Export frames with annotations

### ISSUE THREAD

**Issue by brianrusso** [antingshen/BeaverDam#100]
Great tool.

I need to export frames + annotations  for each so I can train SSD (single shot detector).

It looks like you're storing keyframes + interpolating between them in the Web UI.. is there some existing way to export the interpolated annotations frame by frame?

Figure I'll have to write some code - just looking for help on a starting point. Thanks!

**Comment by antingshen** [comment]
A method in the `Video` class that parses the annotation json and another that interpolates would probably be the cleanest way. You can use the web code as reference. 

A quick hack would be to dump them in the front-end using existing code, if you're short on time.

**Comment by brianrusso** [comment]
Thanks! How do I dump the annotation json?

**Comment by antingshen** [comment]
You can access the json from the Video objects' `.annotation` property through the shell (or any other place in the code). You can use Django's query language to get your set of videos to dump, and get each one's annotation.

**Comment by brianrusso** [comment]
Thanks! That's very helpful. I will do a PR when I get this functionality added.

**Comment by AVCarreiro** [comment]
Any progress regarding this? Or is the best way still to use the front-end code to get the interpolated frames/annotations? Thank you

**Comment by antingshen** [comment]
The best way is probably to write a script to interpolate the keyframe data in the database
