### ISSUE TITLE
Add a new video

### ISSUE THREAD

**Issue by chenfsjz** [antingshen/BeaverDam#102]
I want to use the sample video inside the static/videos/o.mp4. How I should set set the host/filename/source.

**Comment by chenfsjz** [comment]
when I start the server, the browser can't load and play the video.Does anybody knows the reson?

**Comment by antingshen** [comment]
host should be `/static/videos`
filename should be `o.mp4` (`0.mp4`?)
source is optional, for your purposes only. You can check the browser console to see what the error is, likely a 404 on the video.

**Comment by chenfsjz** [comment]
Thanks a lot! I have update the browser, it works normal now.
