### ISSUE TITLE
How to add some code to make action label?

### ISSUE THREAD

**Issue by faj2007** [antingshen/BeaverDam#106]
Hi guys, 
Anyone know how to do this for adding action label in every object(person) in each frame? I am trying and new for this.

**Comment by antingshen** [comment]
The easiest way is to add more classes for each action. You can edit classes by adding and removing `Label` objects, either in `/admin` or in the shell. 

You can also add additional annotation ability for each object, which would require changing the javascript to include a way to add the label, and storing it in the annotation json

**Comment by faj2007** [comment]
Thx for the reply. I prefer the second method. I am learning the django, but still don't know which file should I change. I have add action labels in view.py, models.py and 004_add_label_model.py. It doesn't work out though.

**Comment by antingshen** [comment]
You don't need to change any python files. You just need to change the frontend javascript to store labels in the annotation.

**Comment by clayshieh** [comment]
@faj2007 take a look at #121. Keep in mind this pr doesn't let you add a new field to each frame of an annotation, it only allows you to change the type of each annotation.
