### ISSUE TITLE
HTTP versus HTTPS

### ISSUE THREAD

**Issue by sujiez** [antingshen/BeaverDam#114]
Hi Beaverdam development group,

I am now using Beaverdam to publish some tasks to Amazon Mechanical Turk. When viewing a hit, only request with HTTPs can be accepted by Mturk. However, after attempting, I found current version of Beaverdam only support request with HTTP. Therefore, can you provide some advise about allowing Beaverdam serve HTTPs request, or do you have other suggestion on how to solve this problem? 

Thank you

**Comment by antingshen** [comment]
You will need to set up WSGI (uWSGI, gunicorn) to a webserver like Nginx, for a final setup like this:
Beaverdam <-http/wsgi-> nginx <-https-> mturk

Sample scripts using uWSGI and nginx are provided in `/deployment`

**Comment by sujiez** [comment]
Thank you very much.
