### ISSUE TITLE
How to remove published hit completely

### ISSUE THREAD

**Issue by sujiez** [antingshen/BeaverDam#115]
Hi Beaverdam development team,

When I was trying to publish hits to mturk, I mistakenly published some unsuccessful hits (some cannot be viewed in the "view a hit in current group" popup). After I can publish hits successfully, I deleted all the unsuccessful hit by clicking "delete selected full video task". However, when I try to search my hits on mturk, those unsuccessful hits are still there, which means they still can be viewed. Meanwhile, I found nothing in the mturk requester management page. Therefore, could you provide some way to remove a full video task completely?

Thanks a lot,

**Comment by antingshen** [comment]
Unfortunately, you must call `task.archive_turk_hit()` before deleting the task to tell mturk to disable the HIT. Once the task is deleted on the BeaverDam side, it's pretty difficult to recover the info needed to tell mturk which HIT to delete. 

You can delete ALL of your HITs as follows:
```python
from mturk.models import mturk
mturk.purge()
```

@clayshieh let's make tasks call `archive_turk_hit` when the object is deleted?

**Comment by sujiez** [comment]
I can delete all hits and re-publish. Can you give some advise on where to run the two python code? And should I make a python file which contains the two python command and run it or I should run it in the python shell? Thanks

**Comment by antingshen** [comment]
You can run the python code in the Django shell. Ensure you're in the virtualenv, and run `./manage.py shell`

**Comment by sujiez** [comment]
Thank you a lot for solving my question.
