### ISSUE TITLE
Get all existing video object

### ISSUE THREAD

**Issue by sujiez** [antingshen/BeaverDam#116]
Hi Beaverdam development team,

Could you give me some advise on how to get all existing video object from the ./manage.py shell, so that I can access annotations of videos by accessing .annotation attribute in video objects. 

It's nice to have this great tool, thanks to you guys.

**Comment by antingshen** [comment]
```python
from annotator.models import Video
Video.objects.all()
```

See [QuerySet docs](https://docs.djangoproject.com/en/1.11/ref/models/querysets/) for filtering videos by attributes, etc. I personally like using the `source` to set tags to filter Videos by later
