### ISSUE TITLE
Curves

### ISSUE THREAD

**Issue by bhack** [antingshen/BeaverDam#124]
It would be useful to have splines or bezier curves for segmentation.

See http://paperjs.org/examples/path-simplification/

**Comment by antingshen** [comment]
Segmentation support is a large feature, and is especially complicated to interpolate over video frames, so it's not planned to be added at this time. There are a couple of other tools for image segmentation though

**Comment by bhack** [comment]
Probably there are other tools for image segmentation but video it is more interesting.  Probably you can talk with someone from the [Davis Challenge](http://davischallenge.org/) to check if they are interested to support this extension.
