### ISSUE TITLE
How to use images?

### ISSUE THREAD

**Issue by SebastienLinker** [antingshen/BeaverDam#125]
Hi,

Can you provide an example of how to do the JSON formatting to use images instead of videos?
What are the keywords we need?

**Comment by antingshen** [comment]
Example: `video.image_list = '["20170728_085435.jpg"]'`

**Comment by SebastienLinker** [comment]
Thanks. I submit this text to the image list to make it work:
`["000001.png","000002.png","000003.png"]`
