### ISSUE TITLE
No way to browse hits on Mechanical Turk

### ISSUE THREAD

**Issue by velovix** [antingshen/BeaverDam#127]
BeaverDam submits hits individually instead of as a batch. The Mechanical Turk Requester interface used to have an option to browse these individual hits (albeit marked as deprecated) but has now removed it. Now, we may only browse hits as batches.

It's not really clear to me what this means for BeaverDam. As far as I know, it's impossible to create batches programmatically so it may not be possible to browse BeaverDam hits as a requester at all. Perhaps this aspect of BeaverDam will have to be improved to compensate.

**Comment by antingshen** [comment]
Right, I didn't find a way to create batches programmatically either. Why do you want to browse hits on MTurk? I haven't found myself needing to when using BeaverDam, perhaps there's a feature on MTurk that we can replicate?

**Comment by velovix** [comment]
Now that you mention it, I'm not entirely sure. The project I'm using BeaverDam for is on hold right now, but I will comment on this issue with any features I end up missing once I start using BeaverDam again.
