### ISSUE TITLE
where is the video's annotations?

### ISSUE THREAD

**Issue by zxq309** [antingshen/BeaverDam#131]
Congratulation to your project. when I open the video link and draw rectangle in the first time.after this, how some frame annotations and merge to each frame.Did you achieve tracking like VATIC

**Comment by antingshen** [comment]
I'm not sure what you mean. There's no tracking, just interpolation, but you can add your own tracking if you want

**Comment by antingshen** [comment]
If you're looking for the annotation output, check the `video.annotations`, probably through the python shell
