### ISSUE TITLE
Using management shell to add video objects

### ISSUE THREAD

**Issue by exoticmoose** [antingshen/BeaverDam#146]
Is there any fast tutorial for adding video objects using the Python management shell. I was able to figure out to import the models db from Django, but I'm not familiar enough with Python to get through the whole process. Thanks!

**Comment by antingshen** [comment]
After importing the model class (`Video`) you instantiate it like any other python object: `v = Video(property_a=a, property_b=b)` then call `v.save()` to save it to the database. You can loop over this whole thing as well.

**Comment by exoticmoose** [comment]
Awesome, makes sense now. Thanks!
