### ISSUE TITLE
Be able to set box start & stop times

### ISSUE THREAD

**Issue by antingshen** [antingshen/BeaverDam#25]
Something like draggable brackets in the timeline would be good:
`---[----<>-----<><>-----]------`

**Comment by szhu** [comment]
@antingshen do we still need this? We have start and stop times now, but:
- they're not draggable
- only one range per thing

**Comment by antingshen** [comment]
Probably not? And we don't need to support multiple ranges

**Comment by szhu** [comment]
Great!
