### ISSUE TITLE
Add tutorial

### ISSUE THREAD

**Issue by antingshen** [antingshen/BeaverDam#28]
This includes a popup (or alternative) that has page by page instructions, and a button to re-open this popup.

**Comment by szhu** [comment]
http://github.hubspot.com/shepherd/docs/welcome/ does interactive tutorials easily.

**Comment by allenywang** [comment]
Gabe and I were discussing the steps for the tutorial. At the moment, we wanted to take into consideration object selection, finding the first instance of the object, skipping a few seconds till a major change occurs, all of the shortcuts and controls (deletion, fast forward, rewind, etc), and the submission stage. Anything else? (planning on doing this by creating a video, cropping it, rendering them as gifs, and splitting into separate sections)

**Comment by antingshen** [comment]
There'll probably be things like "how closely do my boxes have to follow the object?" (as accurately as possible, within few pixels) and "why do my boxes not work when they're small" (this we'd need to change when we fix the min size issue @szhu )

**Comment by allenywang** [comment]
Refer to [wiki pages](https://github.com/antingshen/BeaverDam/wiki) for tutorial.
