### ISSUE TITLE
Make UI responsive

### ISSUE THREAD

**Issue by szhu** [antingshen/BeaverDam#39]
Why:
- All the controls should always be visible
- Controls should be smartly placed to reduce mouse move distance
- Lots of awkward blank space sometimes

**Comment by antingshen** [comment]
Note that we can set a "height" attribute for mturk for height of the iframe

**Comment by szhu** [comment]
Ideally, we should make as many of these features as third party-independent as possible. It shouldn't be had to scale the video to fit. But it's okay if we define a reasoning min width/height
