### ISSUE TITLE
Support undo/redo

### ISSUE THREAD

**Issue by szhu** [antingshen/BeaverDam#45]
Ideas:
- client-side undo
- server-side history

**Comment by antingshen** [comment]
client-side redo seems hard and possible not needed.
server-side history seems like a good idea potentially

**Comment by szhu** [comment]
Not hard. We can just keep json history. Undo is good because people make mistakes a lot and undo helps them explore features worry-free so they have a better grasp of the controls.

**Comment by antingshen** [comment]
Closing this for now.. maybe re-open eventually
