### ISSUE TITLE
Rename `Thing` to `Annotation`

### ISSUE THREAD

**Issue by szhu** [antingshen/BeaverDam#48]
and possibly rename `Rect` to `Box`

because we keep calling them that anyway

**Comment by antingshen** [comment]
Maybe we can call "Thing" "Track" because that's what vatic/literature seems to call them...?

**Comment by szhu** [comment]
I want to go with the words we've been using colloquially. It's nice feeling having colloquial speech be technically proper as well.

But specifically, I don't like `Track` because:
- The metaphor makes natural sense to only (1) people who do this kind of research and (2) people familiar with audio and video editing programs. That may be the majority of people we personally know but the average user or perhaps the average future dev on the project might not be familiar with it. Sure, we can take the time to teach them, write docs to explain it, or make sure the UI doesn't show these names to the user, but if we can avoid having two names, then I think it'll take out a lot of thought-overhead.
- The metaphor is associated most strongly with how it appears on screen in the keyframebar, but not as much with the rects that appear onscreen. It's like describing a film as a track rather as a kind of picture (a "motion picture"). I don't think it represents the primary way users view a Thing.
- Track is an extra word to add to people's vocabulary. Everyone who even glances at this app already has the word "annotation" in their head.
