### ISSUE TITLE
Create duplicate box button to make non moving objects easier to track

### ISSUE THREAD

**Issue by clayshieh** [antingshen/BeaverDam#76]
Due to the interpolation between when the car is stopped at a light and when the car starts to move when the light turns green, the box drifts. Should have some sort of functionality to either duplicate the box exactly where it was so that there is no delta in between the two times.

**Comment by antingshen** [comment]
Good issue.. What I've been doing is moving the box a teeny bit on the last frame the car stays still, but is' pretty hacky.

**Comment by clayshieh** [comment]
#112

**Comment by clayshieh** [comment]
merged #112
