### ISSUE TITLE
Need attribute support

### ISSUE THREAD

**Issue by timjr** [antingshen/BeaverDam#97]
It's not clear how to do attributes like Vatic supports.  For example, if I annotate a traffic light, I might like to mark its color.  If I use different labels, like trafficlight-red, trafficlight-green, then they will not be the same object ID, so I would have to merge the tracks.  It is better to have a color attribute in addition to the label that can be red or green.

**Comment by antingshen** [comment]
There's not a feature to do this at the moment. Happy to help look over things if you'd like to add it though :)

**Comment by clayshieh** [comment]
#122

**Comment by jeanineharb** [comment]
Pull request #128 answers this need.
