### ISSUE TITLE
Running BeaverDam outside of Mturk

### ISSUE THREAD

**Issue by akachapati** [antingshen/BeaverDam#99]
Hello. First of all thank you for making the installation process so simple. I was able to get this up and running in no time.

I was wondering though if it's possible to run BeaverDam outside of Mturk. Correct me if I'm wrong, but I should be able to host this somewhere access work from the browser, right? I couldn't figure out how I can upload new content and access output. Any help will be much appreciated. 

Thanks,
Anuj

**Comment by antingshen** [comment]
Yep! Just go to `URL_ROOT/video/<video_id>` to access the view without using mturk. `URL_ROOT` being localhost or wherever you're hosting it. You can also add views to list videos fairly easily.

**Comment by akachapati** [comment]
Thanks. How can I download the output of a task?

**Comment by antingshen** [comment]
The annotations are available at `URL_ROOT/annotation/<video_id>`, or you can access the SQL database directly

**Comment by akachapati** [comment]
That worked, thanks a lot 🥇 
I am very new to this so I was wondering if there's a way to add new videos when running locally. Is there a UI or a script to videos to the database? Thank you for all your help thus far. Really appreciate it.

**Comment by antingshen** [comment]
The UI to add videos is at `/admin`. You can also do whatever you'd like through the shell at `./manage.py shell`. For example, you can instantiate `Video` objects and call `video.save()` on them.

**Comment by akachapati** [comment]
Got it, thank you so much.
